name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    environment: staging

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - name: create env file
        run: |
         touch .env
         echo API_URL=${{ secrets.API_URL }} >> .env
      - run: npm run build --if-present
